### ISSUE TITLE
Fails if not using lightline

### ISSUE THREAD

**Issue by mblarsen** [shapeoflambda/dark-purple.vim#1]
Does not work if one are not using lightline

https://github.com/shapeoflambda/dark-purple.vim/blob/master/colors/dark_purple.vim#L174

**Comment by shapeoflambda** [comment]
Fixed and tested. Let me know if you still see any issues.

**Comment by shapeoflambda** [comment]
Closing this issue as i believe this is fixed. Please feel free to reopen if required.
